# Generated by Django 4.0.5 on 2022-08-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comunidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Usuario')),
                ('producto', models.CharField(max_length=50, verbose_name='Producto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comunidad',
                'ordering': ['-creacion'],
            },
        ),
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=255, verbose_name='Proveedor')),
                ('sugerencia', models.TextField(max_length=255, verbose_name='Sugerencias')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sugerencias',
                'verbose_name_plural': 'Sugerencias',
                'ordering': ['-creacion'],
            },
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Producto')),
                ('categoria', models.CharField(max_length=255, verbose_name='Categoria')),
                ('precio', models.CharField(max_length=255, verbose_name='Precio')),
                ('existencia', models.CharField(max_length=255, verbose_name='Existencia')),
                ('informacion', models.TextField(verbose_name='Informacion')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catalogo',
                'verbose_name_plural': 'Catalogos',
                'ordering': ['-creacion'],
            },
        ),
    ]
